### ISSUE TITLE
Can't swipe away from a video if one is included in the carousel.

### ISSUE THREAD

**Issue by LucasKA** [ixisio/bootstrap-touch-carousel#43]
Great solution on the touch carousel, it works quite brilliantly. However, if you include a video in the carousel, once you swipe to it, you can't swipe away.

It's in the carousel as a bootstrap responsive embed iframe.

I haven't been able to get a solution to where you can still swipe away, but also play the video.

Any suggestions/ideas, or do you have something coming down the pipeline?

**Comment by ixisio** [comment]
hmm, never tried. Have a demo link for me?

**Comment by LucasKA** [comment]
@ixisio Sure, try this on your phone and swipe over to the last entry (video). Then try to swipe away.

Otherwise this is a killer little library man.

**Comment by ixisio** [comment]
oh no, you are right. This has nothing to do with the video, it is caused by the iframe. 
We could not catch swipe events (or any events) on or inside iframes.  A possible solution would be to implement a library like [iFrameCatcher](https://github.com/finalclap/iframeTracker-jquery), but I will not bloat the core with that edge case. 

Sorry man...

**Comment by LucasKA** [comment]
@ixisio I can understand, though this is a for reals problem on the current internets, so if someone comes up with a non bloaty/hacky solution, it could be a big deal.

Still a sweet drop in fix though.

**Comment by ixisio** [comment]
yeah. We have to catch swipe events with a transparent overlay div and pass trough click events to start the video...! 
Found something interesting here: https://github.com/thebird/Swipe/issues/36#issuecomment-66528886
